# Generated by Django 3.2.16 on 2022-10-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
