# Generated by Django 3.2.16 on 2022-10-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0002_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
