# Generated by Django 3.2.16 on 2022-10-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0003_delete_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
