# Generated by Django 3.2.16 on 2022-10-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0004_alter_products_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
