# Generated by Django 3.2.16 on 2022-10-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0006_alter_products_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image2',
        ),
    ]
