# Generated by Django 3.2.16 on 2022-10-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0007_remove_products_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/2'),
        ),
    ]
