# Generated by Django 3.2.16 on 2022-10-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0009_auto_20221027_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/3'),
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/4'),
        ),
    ]
