# Generated by Django 3.2.16 on 2022-11-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0010_auto_20221029_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=300),
        ),
    ]
