# Generated by Django 3.2.16 on 2022-11-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0011_auto_20221101_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='c_offer',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='c_offer_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='p_offer',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='p_offer_price',
            field=models.FloatField(default=0),
        ),
    ]
