# Generated by Django 3.2.16 on 2022-11-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0013_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
