# Generated by Django 3.2.16 on 2022-11-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0014_alter_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='c_offer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_offer',
            field=models.IntegerField(default=0),
        ),
    ]
