# Generated by Django 3.2.16 on 2022-11-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0015_auto_20221114_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='c_offer_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_offer_price',
            field=models.IntegerField(default=0),
        ),
    ]
