# Generated by Django 3.2.16 on 2022-11-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_wishlist',
            field=models.BooleanField(default=True),
        ),
    ]
