# Generated by Django 3.2.16 on 2022-11-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_wishlist_is_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldcart',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
