# Generated by Django 3.2.16 on 2022-11-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_guestcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcart',
            name='cancel',
        ),
        migrations.AddField(
            model_name='guestcart',
            name='user_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
