# Generated by Django 3.2.16 on 2022-11-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20221109_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcart',
            name='user',
        ),
    ]
