# Generated by Django 3.2.16 on 2022-11-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='discount_amount',
        ),
    ]
